

INSERT INTO products (name,price) VALUES('PRODUCTO 1',100);
INSERT INTO products (name,price) VALUES('PRODUCTO 2',200);
INSERT INTO products (name,price) VALUES('PRODUCTO 3',300);
INSERT INTO products (name,price) VALUES('PRODUCTO 4',400);
INSERT INTO products (name,price) VALUES('PRODUCTO 5',500);
INSERT INTO products (name,price) VALUES('PRODUCTO 6',600);
INSERT INTO products (name,price) VALUES('PRODUCTO 7',700);
INSERT INTO products (name,price) VALUES('PRODUCTO 8',800);
INSERT INTO products (name,price) VALUES('PRODUCTO 9',900);
INSERT INTO products (name,price) VALUES('PRODUCTO 10',1000);

INSERT INTO orders(REG_DATE,TOTAL) VALUES(now(),1500);
INSERT INTO order_lines(FK_PRODUCT,PRICE,QUANTITY,TOTAL,FK_ORDER)VALUES(1,100,1,100,1);
INSERT INTO order_lines(FK_PRODUCT,PRICE,QUANTITY,TOTAL,FK_ORDER)VALUES(2,200,1,200,1);
INSERT INTO order_lines(FK_PRODUCT,PRICE,QUANTITY,TOTAL,FK_ORDER)VALUES(3,300,1,300,1);
INSERT INTO order_lines(FK_PRODUCT,PRICE,QUANTITY,TOTAL,FK_ORDER)VALUES(4,400,1,400,1);
INSERT INTO order_lines(FK_PRODUCT,PRICE,QUANTITY,TOTAL,FK_ORDER)VALUES(5,500,1,500,1);

INSERT INTO orders(REG_DATE,TOTAL) VALUES(now(),4000);
INSERT INTO order_lines(FK_PRODUCT,PRICE,QUANTITY,TOTAL,FK_ORDER)VALUES(6,600,1,600,1);
INSERT INTO order_lines(FK_PRODUCT,PRICE,QUANTITY,TOTAL,FK_ORDER)VALUES(7,700,1,700,1);
INSERT INTO order_lines(FK_PRODUCT,PRICE,QUANTITY,TOTAL,FK_ORDER)VALUES(8,800,1,800,1);
INSERT INTO order_lines(FK_PRODUCT,PRICE,QUANTITY,TOTAL,FK_ORDER)VALUES(9,900,1,900,1);
INSERT INTO order_lines(FK_PRODUCT,PRICE,QUANTITY,TOTAL,FK_ORDER)VALUES(10,1000,1,1000,1);


